In [ ]:
pip install gym

In [ ]:
import numpy as np
import gym 
import random 
import time 
from IPython.display import clear_output

In [ ]:
env = gym.make("FrozenLake-v0")

In [ ]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
 
q_table = np.zeros((state_space_size , action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
num_episode = 10000
max_steps_per_episode = 100 # so if agent has not reached frisby by end of 100 episodes then episode will end  with 0 rewards
 
learning_rate = 0.1  # alpha 
discount_rate = 0.99 # gamma
 
 
exploration_rate =1       # epsilon greedy strategy is being used here 
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [ ]:
rewards_all_episodes = [] # 10000 rewards
#q - learning algorithm 
 
for episode in range(num_episode):  #loop for each episode(so 10000 it should run as defined in uper block)
    state = env.reset()   # environment is reset after every episode (detailed reason is yet to be known ie how knownledge on one episode is transfered to another)
    done = False   #this just checks if reset was done or not 
    reward_current_episode = 0 
 
    for step in range(max_steps_per_episode): # this loop tells about what happens at every time step 
        #exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate : 
            action = np.argmax(q_table[state , : ])  # so exploitation occurs and action is taken according to max q value in the table 
        else :
           action = env.action_space.sample()   # here exploration occurs and random action taken 
 
           new_state , reward , done , info = env.step(action) # particular action is send to the env object 
 
           #update q - table for q(s,a)
 
           q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]) - q_table[state, action]) #now here max means that
           #1)when you have got reward for next state then now we to update q table 2) so max here means that step function gives the next state depending on action choosed
           #so in the next state there would be q values depending on differents action so we have to max q - value from current table to update q-table for current state 
           #that means to update q value of current state ,action we need q value of next state,action in currently non - updated q-table 
 
           state  = new_state 
           reward_current_episode+= reward 
 
           if done == True:
              break ; 
 
      #exploration rate decay 
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
        
 
    rewards_all_episodes.append(reward_current_episode)
 
            # Calculate and print the average reward per thousand episodes
    rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),1)
    count = 1000
 
    print("********Average reward per thousand episodes********\n")
    for r in rewards_per_thousand_episodes:
          print(count, ": ", str(sum(r/100)))
          count += 1000

********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per thousand episodes********

1000 :  0.3200000000000001
********Average reward per t

In [ ]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.22392889 0.21229789 0.21858401 0.21754651]
 [0.12621272 0.10368005 0.13545152 0.20535507]
 [0.17168289 0.15011645 0.14936508 0.15362977]
 [0.0536772  0.06225852 0.06304053 0.1139011 ]
 [0.22949612 0.22225902 0.18840044 0.15176949]
 [0.         0.         0.         0.        ]
 [0.16696032 0.03494931 0.15717628 0.04692042]
 [0.         0.         0.         0.        ]
 [0.17477536 0.15259371 0.13473683 0.25019064]
 [0.21864501 0.27958727 0.24878489 0.16851781]
 [0.41626782 0.37357903 0.33232249 0.1031536 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.19652752 0.25417947 0.35632353 0.19606551]
 [0.32354047 0.48216144 0.66516063 0.62855856]
 [0.         0.         0.         0.        ]]


In [ ]:
action_size = env.action_space.n
state_size = env.observation_space.n
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

In [ ]:
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)   
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4881333333333333
[[8.20032681e-02 6.95430875e-02 6.61235207e-02 6.70383332e-02]
 [1.01036245e-02 1.11522224e-02 1.71770760e-02 3.65486358e-02]
 [1.99317888e-02 1.32322958e-02 1.42054428e-02 1.44918704e-02]
 [9.69680782e-03 1.74167238e-03 4.90715860e-03 1.42272179e-02]
 [7.52715637e-02 6.81018381e-02 1.81167384e-02 7.95319762e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.19221752e-04 2.51909170e-09 4.14102148e-02 4.92825740e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.60503260e-02 1.85820162e-02 1.84498198e-02 1.51066098e-01]
 [6.64204796e-02 5.56036173e-01 6.20921576e-02 2.36645164e-02]
 [2.23782667e-02 9.85198564e-03 3.82597717e-01 2.45739104e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.32170321e-02 2.97628976e-02 8.74393397e-01 1.49637797e-04]
 [1.74088445e-01 9.94072815e-01 2.36827641e-01 2.54279396e-01]
 [0.00000000e+00 0.

In [ ]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(qtable)



********Q-table********

[[8.20032681e-02 6.95430875e-02 6.61235207e-02 6.70383332e-02]
 [1.01036245e-02 1.11522224e-02 1.71770760e-02 3.65486358e-02]
 [1.99317888e-02 1.32322958e-02 1.42054428e-02 1.44918704e-02]
 [9.69680782e-03 1.74167238e-03 4.90715860e-03 1.42272179e-02]
 [7.52715637e-02 6.81018381e-02 1.81167384e-02 7.95319762e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.19221752e-04 2.51909170e-09 4.14102148e-02 4.92825740e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [6.60503260e-02 1.85820162e-02 1.84498198e-02 1.51066098e-01]
 [6.64204796e-02 5.56036173e-01 6.20921576e-02 2.36645164e-02]
 [2.23782667e-02 9.85198564e-03 3.82597717e-01 2.45739104e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.32170321e-02 2.97628976e-02 8.74393397e-01 1.49637797e-04]
 [1.74088445e-01 9.94072815e-01 2.36827641e-01 2.54279396e-01]
 [0.00000000e+00 0.00000000e

In [ ]:

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 3
****************************************************
EPISODE  1
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 3
****************************************************
EPISODE  2
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
****************************************************
EPISODE  3
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 6
****************************************************
EPISODE  4
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 3
